cc_library(
    name = "algorithm",
    hdrs = ["Heap.hh",
            "Heap.inl",
            "AdjacentPairRemoval.hh",
            "AdjacentPairRemoval.inl"],
    visibility = ["//visibility:public"]
)
