cc_library(
    name = "algorithm",
    hdrs = ["Heap.hh",
            "Heap.inl",
            "AdjacentPairRemoval.hh",
            "AdjacentPairRemoval.inl",
            "Partition.hh",
            "Partition.inl",
            "NthElement.hh",
            "NthElement.inl"],
    visibility = ["//visibility:public"]
)
