cc_test(
  name = "HeapTest",
  srcs = ["HeapTest.cc"],
  deps = ["//src/algorithm:algorithm",
  "@googletest//:gtest_main"]
)

cc_test(
  name = "AdjacentPairRemovalTest",
  srcs = ["AdjacentPairRemovalTest.cc"],
  deps = ["//src/algorithm:algorithm",
  "@googletest//:gtest_main"]
)
