cc_test(
  name = "TaggedTupleTest",
  srcs = ["TaggedTupleTest.cc"],
  deps = ["//src/containers:containers", "@googletest//:gtest_main"],
)

cc_test(
  name = "VariantTest",
  srcs = ["VariantTest.cc"],
  deps = ["//src/containers:containers", "@googletest//:gtest_main"],
)